# Generated by Django 4.2.23 on 2025-12-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Successful", "Successful"),
                    ("Cancelled", "Cancelled"),
                    ("Processing", "Processing"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
