# Generated by Django 4.2.23 on 2025-12-04 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customerreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bvnverificationattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="blacklistedaccount",
            name="blacklisted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_panel.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="blacklistedaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_users",
                to="admin_panel.adminrole",
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="adminrole",
            index=models.Index(fields=["name"], name="admin_panel_name_55e191_idx"),
        ),
        migrations.AddIndex(
            model_name="adminrole",
            index=models.Index(
                fields=["created_at"], name="admin_panel_created_daf491_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["user"], name="admin_panel_user_id_57a0a4_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type"], name="admin_panel_activit_7340ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["created_at"], name="admin_panel_created_5a7f68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreview",
            index=models.Index(fields=["user"], name="admin_panel_user_id_c84415_idx"),
        ),
        migrations.AddIndex(
            model_name="customerreview",
            index=models.Index(fields=["rating"], name="admin_panel_rating_7d6979_idx"),
        ),
        migrations.AddIndex(
            model_name="customerreview",
            index=models.Index(
                fields=["created_at"], name="admin_panel_created_9d0e60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bvnverificationattempt",
            index=models.Index(fields=["user"], name="admin_panel_user_id_d30352_idx"),
        ),
        migrations.AddIndex(
            model_name="bvnverificationattempt",
            index=models.Index(fields=["status"], name="admin_panel_status_aa1515_idx"),
        ),
        migrations.AddIndex(
            model_name="bvnverificationattempt",
            index=models.Index(
                fields=["created_at"], name="admin_panel_created_1709c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blacklistedaccount",
            index=models.Index(fields=["user"], name="admin_panel_user_id_2fb197_idx"),
        ),
        migrations.AddIndex(
            model_name="blacklistedaccount",
            index=models.Index(
                fields=["is_active"], name="admin_panel_is_acti_b230e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blacklistedaccount",
            index=models.Index(
                fields=["blacklisted_at"], name="admin_panel_blackli_d0e014_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminuser",
            index=models.Index(
                fields=["is_super_admin"], name="admin_panel_is_supe_e19288_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminuser",
            index=models.Index(
                fields=["created_at"], name="admin_panel_created_e3bbde_idx"
            ),
        ),
    ]
