# Generated by Django 4.2.23 on 2025-12-08 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="active",
        ),
    ]
