# Generated by Django 4.2.23 on 2025-10-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
