# Generated by Django 4.2.23 on 2025-10-17 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_userprofile_is_verified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="user",
            table="home_user",
        ),
    ]
