# Generated by Django 4.2.23 on 2025-10-17 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
