# Generated by Django 4.2.23 on 2025-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
