# Generated by Django 4.2.23 on 2025-10-26 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_userprofile_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userotp",
            name="userprofile",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
