# Generated by Django 4.2.23 on 2025-12-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_alter_cart_status"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorSalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("new_customers", models.PositiveIntegerField(default=0)),
                ("returning_customers", models.PositiveIntegerField(default=0)),
                ("orders_count", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_records",
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "date"], name="vendors_ven_vendor__742c5c_idx"
                    )
                ],
                "unique_together": {("vendor", "date")},
            },
        ),
        migrations.CreateModel(
            name="VendorNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order", "New Order"),
                            ("low_stock", "Low Stock Alert"),
                            ("out_of_stock", "Out of Stock"),
                            ("review", "New Review"),
                            ("payment", "Payment Received"),
                            ("system", "System Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "-created_at"],
                        name="vendors_ven_vendor__33bd02_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="vendors_ven_is_read_5346d4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "weekly_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monthly_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("pending_orders", models.PositiveIntegerField(default=0)),
                ("successful_orders", models.PositiveIntegerField(default=0)),
                ("cancelled_orders", models.PositiveIntegerField(default=0)),
                ("total_products", models.PositiveIntegerField(default=0)),
                ("out_of_stock_products", models.PositiveIntegerField(default=0)),
                ("low_stock_products", models.PositiveIntegerField(default=0)),
                ("total_customers", models.PositiveIntegerField(default=0)),
                ("returning_customers", models.PositiveIntegerField(default=0)),
                (
                    "returning_customer_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gross_sale",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "refunds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "processing_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "-date"],
                        name="vendors_ven_vendor__02723d_idx",
                    ),
                    models.Index(fields=["date"], name="vendors_ven_date_837474_idx"),
                ],
                "unique_together": {("vendor", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProductPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_quantity_sold", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "order_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "revenue_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("wishlist_count", models.PositiveIntegerField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="stock.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_revenue"],
                "indexes": [
                    models.Index(
                        fields=["-total_revenue"], name="vendors_pro_total_r_6fd7ed_idx"
                    ),
                    models.Index(
                        fields=["-total_orders"], name="vendors_pro_total_o_39a856_idx"
                    ),
                ],
            },
        ),
    ]
